{% set name = "pymt_ecsimplesnow" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: bb381366544876ed39fe54ab8085b0a5659fbc1be101e60d7d3e8d77279b9e7c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [win]
  skip: true  # [unix and py<=35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy >=1.14
    - model_metadata
    - bmi-fortran =1.2
    - ecsimplesnow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmi-fortran =1.2
    - ecsimplesnow

test:
  imports:
    - pymt_ecsimplesnow

about:
  home: https://github.com/pymt-lab/pymt_ecsimplesnow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the ECSimpleSnow model.
  dev_url: https://github.com/pymt-lab/pymt_ecsimplesnow

extra:
  recipe-maintainers:
    - mdpiper
