{% set name = "pymt_ecsimplesnow" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3319a8883306c3739f5efcb8680f8701d49da02bff72f8d8496eebaaddfa2e35

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win and vc<14]
  skip: true  # [unix and py<=35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy >=1.14
    - model_metadata
    - bmi-fortran =1.2
    - ecsimplesnow
  run:
    - python >=3
    - {{ pin_compatible('numpy') }}
    - bmi-fortran =1.2
    - ecsimplesnow

test:
  imports:
    - pymt_ecsimplesnow

about:
  home: https://github.com/pymt-lab/pymt_ecsimplesnow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the ECSimpleSnow model.
  dev_url: https://github.com/pymt-lab/pymt_ecsimplesnow

extra:
  recipe-maintainers:
    - mdpiper
