{% set name = "pymt_ecsimplesnow" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f62c8112dbacfc2a65c45c63bb3c3cfdd22dee4f943ace47ab64e88cd54eb502

build:
  number: 6
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [win]
  skip: true  # [unix and py<=35]
  skip: true  # [py>=312]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy >=1.14
    - model_metadata
    - bmi-fortran =1.2
    - ecsimplesnow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmi-fortran =1.2
    - ecsimplesnow

test:
  imports:
    - pymt_ecsimplesnow

about:
  home: https://github.com/pymt-lab/pymt_ecsimplesnow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the ECSimpleSnow model.
  dev_url: https://github.com/pymt-lab/pymt_ecsimplesnow

extra:
  recipe-maintainers:
    - mdpiper
