{% set name = "pymt_ecsimplesnow" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b558bd7fbb08310242995666f4c4e1e70900eff8536422e31dd3de90cc77245e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - model_metadata
    - bmi-fortran =1.2
    - ecsimplesnow
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - bmi-fortran =1.2
    - ecsimplesnow

test:
  imports:
    - pymt_ecsimplesnow

about:
  home: https://github.com/pymt-lab/pymt_ecsimplesnow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the ECSimpleSnow model.
  dev_url: https://github.com/pymt-lab/pymt_ecsimplesnow

extra:
  recipe-maintainers:
    - mdpiper
