{% set name = "pymt_ecsimplesnow" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f62c8112dbacfc2a65c45c63bb3c3cfdd22dee4f943ace47ab64e88cd54eb502

build:
  number: 10
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [win and vc<14]
  skip: true  # [unix and py<=35]
  skip: true  # [py>=312]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - setuptools <60.0
    - cython
    - numpy <2
    - model_metadata =0.7.0
    - bmi-fortran =1.2.1
    - ecsimplesnow
  run:
    - python
    - bmi-fortran =1.2.1
    - ecsimplesnow

test:
  imports:
    - pymt_ecsimplesnow

about:
  home: https://github.com/pymt-lab/pymt_ecsimplesnow
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the ECSimpleSnow model.
  dev_url: https://github.com/pymt-lab/pymt_ecsimplesnow

extra:
  recipe-maintainers:
    - mdpiper
