travis:
  secure:
    BINSTAR_TOKEN: kCdLrx5JCOVAYYaY1DSlVw7JRWn8YiZFhC50nTIdQIS2GtmQ35JVc/09v2tiED1Rq5xHROhlWQKVMudz84i8VIw4BtCxrZVJB7YAIL8fVMJAAc4ZdgTiOaeuISeD9uGfZPoDbQn5gG5bp8sbl9iJlbcFc9TdM3T8u1JUvbONIz/yxIT2kgmSvy9H8DIHXGhFujjHa0sUvW5Wg5R2s/o4QwHqn4II5HgS61X66FKT7Hu7v0nngPjxiqxGo5hJkOT1f54rpBHKM0DAX9X21NEIm7UdXDxnVjogohgk5KQNVnqbTktt+5wmBl7Zp0UPvW4fNp0CQcmNEL2yRv/5dkQZwiib9ycRk/wxf+1wi95gRMJ1qzflTtZ+hdU8RlBtAi85EI10glzUdnvP6LGaT8JwuB1BSYOcISvdb78f1k1rVDYB9bQFx8P0D3LxCpe6cX5OGaAxS1XySH28ld7KLl2a/Eweh2PPqK8XlXXXjZs19U/syJvDCmrT8db30h65ocb/BcImeomzRqZ5Eh2f5j9FYcyLil3R2IzuBqJUOX/j2DWf1/xORMTQF7w5uk1SlplRarY+A/D5eTNp1q+tgyzGNOr1o6+BcvJ/HfEhwVvPCoIFoir5xbXURes0lveY0BZdrQI0phBTytuCVcT5aCON7me80+560GapFmskvFMLMp4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
