travis:
  secure:
    BINSTAR_TOKEN: E/iUiRWb5S4NvPsjdZJ7/R8ByRaQYWJJs7Zk97liFqxpivhOQxGyAMIS/e/8cAcr5NDgw8zGh3kclNPP9zblAug91dWRVOo2yAaHc9BayTjG+CVFfvmZ/F6eAKRB3ewM/qdhHFhnQ1QJZ1wbA1Hj4JUIm8lkajyHUK18SNE3I/XwzIh1z/PEWOparaibChQjh4zoc7yk0kuQLTDdS4AtWFMJU1u3Yg/f0EYrwWjin9kGigPBDcNfeZO/4SzNgV5sf+w/7013xa+ng5KPL1RzElh360FOO6NkQywGMnHe6SiVZOUBbXnaNFWIduG/O0O7TRgSP3Bvsbn1gx4oMgAjVtcy23pTMt8E33cSFEe3Fu0q322WoMtDBswaSCjZeplFLhoC1gDQsuTCfJbr36XAh7qzAob1qHcl3q310KQjXzrh5fUxeLFCet2cQ2EO00PPkHk8evlN1wKBOIHtyEJWDepNpFyHvgVdE8bxIZxqEO+MkwOBDt5yWhRlMDxODcVPaNOQ01J5FuPT4tkyjPeiGp0ACIzSXGtFVB+9zUUGY+r/FbW2L/xPQLog6cGHhRLGygHvFgrUEpj5t6m0cO1PVqqWowsVPGpKegioRuaA/qPEQUhckxNsQhwTbKPdIL49LCq/p0CkySUwuZ1w8Y/H1YoLjbpXIxylCh0/T7acfJU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
